kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: clinical
  labels:
    strimzi.io/cluster: cockroachcluster
  namespace: openshift-operators
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824

