apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
  labels:
    app: redpanda
spec:
  selector:
    #app.kubernetes.io/name: redpanda-kafka
    app.kubernetes.io/name: redpanda
  ports:
  - protocol: "TCP"
    port: 9092
    name: kafka
  type: LoadBalancer

